- name: play1
  hosts: web_servers
  gather_facts: true
  tasks:
  - name: ping with save output
    ping:
    register: output
    #when: ansible_facts["distribution"] == "Ubuntu"
  
  - name: print saved output
    debug:
        var: output
  
  - name: cd and ignore the error 
    command: cd mydir
    ignore_errors: true
    #when: ansible_facts["distribution"] == "Ubuntu"
  
  
  - name: cd and rescue the error 
    block:
      - command: cd mydir
        register: output
    rescue:
      - debug:
          msg: "{{ output }}"
    #when: ansible_facts["distribution"] == "Ubuntu"

  - name: apt update
    apt:
      update_cache: true

  - name: install latest nginx
    apt:
      name: nginx
      state: latest
  
  - name: copy index
    copy:
      src: ./index.html
      dest: /var/www/html/index.html
  
  - name: restart nginx
    sysvinit:
      name: nginx
      state: restarted
      

  
  
  